spring:
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password: passw0rd
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/easy_code?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: passw0rd
  data:
    mongodb:
      uri: mongodb://admin:passw0rd@127.0.0.1:27017/log