server:
  port: 8181
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
  application:
    name: easy-code


# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

# jwt 秘钥
jwt:
  secret: easycodepassw0rd.
  expireTime: 86400000 # 24 hour | 毫秒
  headerKeyPrefix: Authorization
  headerValuePrefix: Bearer

# 密码 盐
login:
  salt: passw0rd

#白名单 给拦截器使用(登录、注册接口、接口文档、druid等)
ignore:
  urls:
    - /user/login
    - /user/register
    - /doc.html
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /v2/api-docs
    - /webjars/**
    - /favicon.ico
    - /actuator/**
    - /druid/**

# 日志
logging:
  level:
    com.chz.mapper: debug
    com.yi.easycode: debug


# 自定义秘钥
# customerKey 切勿随便修改，因为需要满足AES的密钥长度规则(128bit、256bit等等)，但是Java中默认只支持128bit
# 如果想修改 https://blog.csdn.net/z69183787/article/details/82746686
# 一个英文字符为一个byte位  一个 byte 等于 8 bit 16 byte * 8 bit = 128
easycodeSecret:
  easy-code-secret